=== gizela/gizela/xml/gama-local.dtd
<!-- ****************************************************************

gama-local.dtd                     version 2.0.14  2007-01-20
==============

2.0.14  2007-01-20

      - gama-xml.dtd renamed to gama-local.dtd

      - changed type of distance-stdev attribute to CDATA
         <    distance-stdev      NMTOKEN  #IMPLIED
         >    distance-stdev      CDATA    #IMPLIED

2.0.13  2006-02-12

      - added new optional attribute  epoch NMTOKEN "0.0"
        into tag <network>

2.0.12  2004-03-30

      - added new attribute update-constrained-coordinates = "no | yes"
        into tag <parameters />

      - added new attribute zenith-angle-stdev into <points-observations />

2.0.11  2002-06-27

      - added attributes for describing heights of instrument and/or
        reflector: from_dh="...", to_dh="...", bs_dh="..." and
        fs_dh="..."

2.0.10  2002-05-24

      - new attributes bs="..." and fs="..." in the definition of <angle />

        Chuck Ghilani pointed out that XML description of angles was
        not natural; thus attribute `to' was renamed to `bs' (backsight) 
        and `rs' was renamed to `fs' (foresight)

2.0.09  2002-01-03

      - corrected definition of point attributes fix and adj

2.0.08  2001-08-20

      - added attributes axes-xy and angles into tag <network>

2.0.07  2001.06.27

      - removed parameters txt, stx, opr and xy (for the time being 
        are accepted by gama for backward compatibility)

      - introduced new parameters <point fix="..." and adj="..." />

      - tag <dh /> allowed inside start-end tag <obs>

2.0.06  2001.04.27

      - new tags: s-distance, z-angle, height-differences, dh,
        vectors, vec

2.0.05  2001.04.24

      - deterministic bug in elements obs and coordinates (Kolda)

2.0.04  2001.04.24

      - added attribute version into tag gama-local

2.0.03  2001.04.17

      - corrected two errors concerning cov-mat (Jan Kolar, Jan Pytel)

2.0.02  2001.02.22

      - attribute `at' renamed to `from'

2.0.01  2001.02.16

      - attribute type `at' of the element `obs' changed to #IMPLIED
        (we do not need a station number for the set of angles or height
        differences)

2.0.00  2000.08.24 English tag names replaced their Czech equivalents
      (thanks to Pavel Novak for consultations)

      This version was translated from version 1.03 using sed editor

            s/sit/network/g
            s/popis/description/g
            s/parametry/parameters/g
            s/body-mereni/points-observations/g
            
            # delka-str-km delka-str-exp  .... removed
            s/str/stdev/g
            
            s/bod/point/g
            s/cislo/id/g
            s/typ/xy/g
            s/or-posun/orientation/g
            
            s/pevny/fixed/g
            s/urcovany/free/g
            s/operny/constrained/g
            s/nepouzit/unused/g
            
            s/konf-pr/conf-pr/g
            s/m0-apr/sigma-apr/g
            s/type-m0/sigma-act/g
            s/empiricka/aposteriori/g
            s/apriorni/apriori/g


1.03  2000.08.01 preparation for version 2.0 : single distances and 
      angles cannot be used outside tag <body-mereni>, removed tags 
      <delka-str-km> and <delka-str-exp> 

      added new tags:
      ==============
        
      * tag <cov-mat>       (covariance matrix of observations)
      * tag <coordinates>   (coordinate observations)


1.02  2000.04.15 types of numerical attributes changed  from CDATA
      to NMTOKEN (Miloslav Nic)

1.01  2000.03.28 to the element osnova added element uhel

1.00  1999.07.05 first draft (Ales Cepek)


***********************************************************************

Definition of XML input stream for GNU GaMa for adjustment of local
geodetic network. Latest version is available from

            http://www.gnu.org/software/gama/gama-local.dtd

GNU GaMa is subject to GNU General Public Licence, for more
information visit

            http://www.gnu.org/software/gama/

*********************************************************************** -->

<!ELEMENT  gama-local     (network) >
<!ELEMENT  network      (description | parameters | points-observations)* >
<!ELEMENT  description  (#PCDATA) >
<!ELEMENT  parameters   EMPTY >
<!ELEMENT  points-observations  (point | obs | coordinates | 
                                 height-differences | vectors)* >
<!ELEMENT  point  EMPTY >

<!ELEMENT  obs ((direction | distance | angle | s-distance | z-angle 
                | dh)*, cov-mat?) >

<!ELEMENT  cov-mat  (#PCDATA) >

<!ELEMENT  direction   EMPTY >
<!ELEMENT  distance    EMPTY >
<!ELEMENT  angle       EMPTY >
<!ELEMENT  s-distance  EMPTY >
<!ELEMENT  z-angle     EMPTY >

<!ELEMENT  height-differences (dh+, cov-mat?) >
<!ELEMENT  dh  EMPTY >

<!-- observed coordinates -->
<!ELEMENT  coordinates (point+, cov-mat) >

<!-- observed coordinate differences -->
<!ELEMENT  vectors     (vec+, cov-mat) >  
<!ELEMENT  vec          EMPTY > 

<!ATTLIST gama-local version NMTOKEN #IMPLIED >

<!ATTLIST network

   axes-xy (ne | sw | es | wn | 
            en | nw | se | ws )          "ne"
   angles  (right-handed | left-handed)  "right-handed" 
   epoch    NMTOKEN                      "0.0" >

<!ATTLIST parameters 

   sigma-apr  NMTOKEN  "10.0" 
   conf-pr    NMTOKEN  "0.95"
   tol-abs    NMTOKEN  "1000.0"
   sigma-act           (aposteriori | apriori) "apriori" 
   update-constrained-coordinates   (yes | no) "no" >

<!ATTLIST points-observations

   distance-stdev      CDATA    #IMPLIED
   direction-stdev     NMTOKEN  #IMPLIED
   angle-stdev         NMTOKEN  #IMPLIED
   zenith-angle-stdev  NMTOKEN  #IMPLIED  >

<!ATTLIST point

   id  CDATA    #REQUIRED
   x   NMTOKEN  #IMPLIED
   y   NMTOKEN  #IMPLIED
   z   NMTOKEN  #IMPLIED
   fix (xy | XY | z | Z | xyz | XYZ | XYz | xyZ ) #IMPLIED
   adj (xy | XY | z | Z | xyz | XYZ | XYz | xyZ ) #IMPLIED >

<!ATTLIST obs    
   from         CDATA   #IMPLIED
   orientation  NMTOKEN #IMPLIED  
   from_dh      NMTOKEN #IMPLIED >

<!ATTLIST cov-mat
   dim   NMTOKEN  #REQUIRED
   band  NMTOKEN  #REQUIRED >

<!ATTLIST direction 

   to       CDATA    #REQUIRED
   val      NMTOKEN  #REQUIRED
   stdev    NMTOKEN  #IMPLIED  
   from_dh  NMTOKEN  #IMPLIED
   to_dh    NMTOKEN  #IMPLIED  >

<!ATTLIST distance 

   from     CDATA    #IMPLIED
   to       CDATA    #REQUIRED
   val      NMTOKEN  #REQUIRED
   stdev    NMTOKEN  #IMPLIED  
   from_dh  NMTOKEN  #IMPLIED
   to_dh    NMTOKEN  #IMPLIED >

<!ATTLIST angle 

   from     CDATA    #IMPLIED
   bs       CDATA    #REQUIRED
   fs       CDATA    #REQUIRED
   val      NMTOKEN  #REQUIRED
   stdev    NMTOKEN  #IMPLIED  
   from_dh  NMTOKEN  #IMPLIED
   bs_dh    NMTOKEN  #IMPLIED 
   fs_dh    NMTOKEN  #IMPLIED >

<!ATTLIST s-distance

   from     CDATA    #IMPLIED
   to       CDATA    #REQUIRED
   val      NMTOKEN  #REQUIRED
   stdev    NMTOKEN  #IMPLIED  
   from_dh  NMTOKEN  #IMPLIED
   to_dh    NMTOKEN  #IMPLIED >

<!ATTLIST z-angle

   from     CDATA    #IMPLIED
   to       CDATA    #REQUIRED
   val      NMTOKEN  #REQUIRED
   stdev    NMTOKEN  #IMPLIED  
   from_dh  NMTOKEN  #IMPLIED
   to_dh    NMTOKEN  #IMPLIED >
   
<!ATTLIST dh

   from   CDATA    #IMPLIED
   to     CDATA    #REQUIRED
   val    NMTOKEN  #REQUIRED
   stdev  NMTOKEN  #IMPLIED  
   dist   NMTOKEN  #IMPLIED >
   
<!ATTLIST vec

   from     CDATA    #IMPLIED
   to       CDATA    #REQUIRED
   dx       NMTOKEN  #REQUIRED
   dy       NMTOKEN  #REQUIRED
   dz       NMTOKEN  #REQUIRED 
   from_dh  NMTOKEN  #IMPLIED
   to_dh    NMTOKEN  #IMPLIED >

=== gizela/gizela/example/xml-corr/xml-corr2.corrected.xml
<?xml version="1.0" ?>
<!DOCTYPE gama-xml
SYSTEM "http://www.gnu.org/software/gama/gama-local.dtd">
<gama-local>
<network axes-xy="ne" angles="right-handed">
<description>
[epoch]
date = 
description = Correction testing network - the cube

</description>
<parameters sigma-apr = "1.000"
            conf-pr   = "0.950"
            sigma-act = "apriori"/>
<points-observations direction-stdev="10.0" distance-stdev="10.0" zenith-angle-stdev="10.0">
<point id="222" x="2000.0000" y="2000.0000" z="2000.0000" fix="xyz" />
<point id="111" x="1000.0000" y="1000.0000" z="1000.0000" adj="xyz" />
<point id="121" x="1000.0000" y="2000.0000" z="1000.0000" adj="xyz" />
<point id="131" x="1000.0000" y="3000.0000" z="1000.0000" adj="xyz" />
<point id="211" x="2000.0000" y="1000.0000" z="1000.0000" adj="xyz" />
<point id="231" x="2000.0000" y="3000.0000" z="1000.0000" adj="xyz" />
<point id="311" x="3000.0000" y="1000.0000" z="1000.0000" adj="xyz" />
<point id="321" x="3000.0000" y="2000.0000" z="1000.0000" adj="xyz" />
<point id="331" x="3000.0000" y="3000.0000" z="1000.0000" adj="xyz" />
<point id="112" x="1000.0000" y="1000.0000" z="2000.0000" adj="XYZ" />
<point id="122" x="1000.0000" y="2000.0000" z="2000.0000" adj="xyz" />
<point id="132" x="1000.0000" y="3000.0000" z="2000.0000" adj="xyz" />
<point id="212" x="2000.0000" y="1000.0000" z="2000.0000" adj="xyz" />
<point id="232" x="2000.0000" y="3000.0000" z="2000.0000" adj="xyz" />
<point id="312" x="3000.0000" y="1000.0000" z="2000.0000" adj="xyz" />
<point id="322" x="3000.0000" y="2000.0000" z="2000.0000" adj="xyz" />
<point id="332" x="3000.0000" y="3000.0000" z="2000.0000" adj="xyz" />
<point id="113" x="1000.0000" y="1000.0000" z="3000.0000" adj="xyz" />
<point id="123" x="1000.0000" y="2000.0000" z="3000.0000" adj="xyz" />
<point id="133" x="1000.0000" y="3000.0000" z="3000.0000" adj="xyz" />
<point id="213" x="2000.0000" y="1000.0000" z="3000.0000" adj="xyz" />
<point id="233" x="2000.0000" y="3000.0000" z="3000.0000" adj="xyz" />
<point id="313" x="3000.0000" y="1000.0000" z="3000.0000" adj="xyz" />
<point id="323" x="3000.0000" y="2000.0000" z="3000.0000" adj="xyz" />
<point id="333" x="3000.0000" y="3000.0000" z="3000.0000" adj="xyz" />
<obs from="222" >
	<direction to="111" val="0.00000" />
	<direction to="211" val="49.97998" />
	<direction to="311" val="99.97997" />
	<direction to="321" val="149.97998" />
	<direction to="331" val="200.00000" />
	<direction to="231" val="250.02002" />
	<direction to="131" val="300.02003" />
	<direction to="121" val="350.02002" />
	<z-angle to="111" val="139.16168" />
	<z-angle to="131" val="139.19000" />
	<z-angle to="311" val="139.19000" />
	<z-angle to="331" val="139.21832" />
	<z-angle to="211" val="149.97998" />
	<z-angle to="321" val="150.02002" />
	<z-angle to="231" val="150.02002" />
	<z-angle to="121" val="149.97998" />
	<s-distance to="111" val="1732.00000" />
	<s-distance to="311" val="1732.00000" />
	<s-distance to="331" val="1732.00000" />
	<s-distance to="131" val="1732.00000" />
	<s-distance to="211" val="1414.00000" />
	<s-distance to="321" val="1414.00000" />
	<s-distance to="231" val="1414.00000" />
	<s-distance to="121" val="1414.00000" />
	<direction to="112" val="-0.00000" />
	<direction to="212" val="50.00000" />
	<direction to="312" val="100.00000" />
	<direction to="322" val="150.00000" />
	<direction to="332" val="200.00000" />
	<direction to="232" val="250.00000" />
	<direction to="132" val="300.00000" />
	<direction to="122" val="350.00000" />
	<z-angle to="112" val="99.97168" />
	<z-angle to="212" val="99.97998" />
	<z-angle to="312" val="100.00000" />
	<z-angle to="322" val="100.02002" />
	<z-angle to="332" val="100.02832" />
	<z-angle to="232" val="100.02002" />
	<z-angle to="132" val="100.00000" />
	<z-angle to="122" val="99.97998" />
	<s-distance to="112" val="1414.00000" />
	<s-distance to="312" val="1414.00000" />
	<s-distance to="332" val="1414.00000" />
	<s-distance to="132" val="1414.00000" />
	<s-distance to="212" val="1000.00000" />
	<s-distance to="322" val="1000.00000" />
	<s-distance to="232" val="1000.00000" />
	<s-distance to="122" val="1000.00000" />
	<direction to="113" val="-0.00000" />
	<direction to="213" val="50.02002" />
	<direction to="313" val="100.02003" />
	<direction to="323" val="150.02002" />
	<direction to="333" val="200.00000" />
	<direction to="233" val="249.97998" />
	<direction to="133" val="299.97997" />
	<direction to="123" val="349.97998" />
	<z-angle to="113" val="60.78168" />
	<z-angle to="133" val="60.81000" />
	<z-angle to="313" val="60.81000" />
	<z-angle to="333" val="60.83832" />
	<z-angle to="213" val="49.97998" />
	<z-angle to="323" val="50.02002" />
	<z-angle to="233" val="50.02002" />
	<z-angle to="123" val="49.97998" />
	<s-distance to="113" val="1732.00000" />
	<s-distance to="313" val="1732.00000" />
	<s-distance to="333" val="1732.00000" />
	<s-distance to="133" val="1732.00000" />
	<s-distance to="213" val="1414.00000" />
	<s-distance to="323" val="1414.00000" />
	<s-distance to="233" val="1414.00000" />
	<s-distance to="123" val="1414.00000" />
</obs>
</points-observations>
</network>
</gama-local>

=== gizela/gizela/example/xml-corr/xml-corr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gama-local SYSTEM "../../../gama-1.9.07/xml/gama-local.dtd" >
<gama-local>
	<network angles="left-handed" axes-xy="en">
		<description>Correction testing network</description>		
		<parameters conf-pr="0.95" sigma-act="apriori" sigma-apr="1.00"
			update-constrained-coordinates="no" />
		<points-observations>
			<point id="0" x="0" y="0" z="0" fix="xyz" />
			<point id="2" x="1000" y="1000" z="1000" adj="XY" />
			<point id="4" x="-1000" y="1000" z="0" adj="XY" />
			<point id="6" x="-1000" y="-1000" z="0" adj="XY" />
			<point id="8" x="1000" y="-1000" z="0" adj="XY" />
			<obs>
				<distance from="0" to="2" val="1414.213562" />
				<distance from="0" to="4" val="1414.213562" />
				<distance from="0" to="6" val="1414.213562" />
				<distance from="0" to="8" val="1414.213562" />
				<distance from="2" to="4" val="2000" />
				<distance from="4" to="6" val="2000" />
				<distance from="6" to="8" val="2000" />
				<distance from="8" to="2" val="2000" />
			</obs>
			<obs from="0">
				<direction to="2" val="0" />
				<direction to="4" val="100" />
				<direction to="6" val="200" />
				<direction to="8" val="300" />
			</obs>
			<obs from="2">
				<direction to="8" val="0" />
				<direction to="0" val="50" />
				<direction to="4" val="100" />
			</obs>
			<obs from="4">
				<direction to="2" val="0" />
				<direction to="0" val="50" />
				<direction to="6" val="100" />
			</obs>
			<obs from="6">
				<direction to="4" val="0" />
				<direction to="0" val="50" />
				<direction to="8" val="100" />
			</obs>
			<obs from="8">
				<direction to="6" val="0" />
				<direction to="0" val="50" />
				<direction to="2" val="100" />
			</obs>
		</points-observations>
	</network>
</gama-local>

=== gizela/gizela/example/xml-corr/xml-corr2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gama-local SYSTEM "../../../gama-1.9.07/xml/gama-local.dtd" >
<gama-local>
  <network angles="left-handed" axes-xy="en">
    <description>Correction testing network - the cube</description>
    <parameters conf-pr="0.95" sigma-act="apriori" sigma-apr="1.00"
      update-constrained-coordinates="no" />
    <points-observations direction-stdev="10" 
	                 distance-stdev="10"
			 zenith-angle-stdev="10">
      <point id="222" x="2000" y="2000" z="2000" fix="xyz" />

      <point id="111" x="1000" y="1000" z="1000" adj="xyz" />
      <point id="121" x="1000" y="2000" z="1000" adj="xyz" />
      <point id="131" x="1000" y="3000" z="1000" adj="xyz" />
      <point id="211" x="2000" y="1000" z="1000" adj="xyz" />
      <point id="231" x="2000" y="3000" z="1000" adj="xyz" />
      <point id="311" x="3000" y="1000" z="1000" adj="xyz" />
      <point id="321" x="3000" y="2000" z="1000" adj="xyz" />
      <point id="331" x="3000" y="3000" z="1000" adj="xyz" />

      <point id="112" x="1000" y="1000" z="2000" adj="XYZ" />
      <point id="122" x="1000" y="2000" z="2000" adj="xyz" />
      <point id="132" x="1000" y="3000" z="2000" adj="xyz" />
      <point id="212" x="2000" y="1000" z="2000" adj="xyz" />
      <point id="232" x="2000" y="3000" z="2000" adj="xyz" />
      <point id="312" x="3000" y="1000" z="2000" adj="xyz" />
      <point id="322" x="3000" y="2000" z="2000" adj="xyz" />
      <point id="332" x="3000" y="3000" z="2000" adj="xyz" />

      <point id="113" x="1000" y="1000" z="3000" adj="xyz" />
      <point id="123" x="1000" y="2000" z="3000" adj="xyz" />
      <point id="133" x="1000" y="3000" z="3000" adj="xyz" />
      <point id="213" x="2000" y="1000" z="3000" adj="xyz" />
      <point id="233" x="2000" y="3000" z="3000" adj="xyz" />
      <point id="313" x="3000" y="1000" z="3000" adj="xyz" />
      <point id="323" x="3000" y="2000" z="3000" adj="xyz" />
      <point id="333" x="3000" y="3000" z="3000" adj="xyz" />

      <obs from="222">
        <direction to="111" val="0" />
        <direction to="211" val="50" />
        <direction to="311" val="100" />
        <direction to="321" val="150" />
        <direction to="331" val="200" />
        <direction to="231" val="250" />
        <direction to="131" val="300" />
        <direction to="121" val="350" />

	<z-angle to="111" val="139.19"/>
	<z-angle to="131" val="139.19"/>
	<z-angle to="311" val="139.19"/>
	<z-angle to="331" val="139.19"/>
	<z-angle to="211" val="150"/>
	<z-angle to="321" val="150"/>
	<z-angle to="231" val="150"/>
	<z-angle to="121" val="150"/>

        <s-distance to="111" val="1732" />
        <s-distance to="311" val="1732" />
        <s-distance to="331" val="1732" />
        <s-distance to="131" val="1732" />
        <s-distance to="211" val="1414" />
        <s-distance to="321" val="1414" />
        <s-distance to="231" val="1414" />
        <s-distance to="121" val="1414" />

        <direction to="112" val="0" />
        <direction to="212" val="50" />
        <direction to="312" val="100" />
        <direction to="322" val="150" />
        <direction to="332" val="200" />
        <direction to="232" val="250" />
        <direction to="132" val="300" />
        <direction to="122" val="350" />

	<z-angle to="112" val="100"/>
	<z-angle to="212" val="100"/>
	<z-angle to="312" val="100"/>
	<z-angle to="322" val="100"/>
	<z-angle to="332" val="100"/>
	<z-angle to="232" val="100"/>
	<z-angle to="132" val="100"/>
	<z-angle to="122" val="100"/>

        <s-distance to="112" val="1414" />
        <s-distance to="312" val="1414" />
        <s-distance to="332" val="1414" />
        <s-distance to="132" val="1414" />
        <s-distance to="212" val="1000" />
        <s-distance to="322" val="1000" />
        <s-distance to="232" val="1000" />
        <s-distance to="122" val="1000" />

        <direction to="113" val="0" />
        <direction to="213" val="50" />
        <direction to="313" val="100" />
        <direction to="323" val="150" />
        <direction to="333" val="200" />
        <direction to="233" val="250" />
        <direction to="133" val="300" />
        <direction to="123" val="350" />

	<z-angle to="113" val="60.81"/>
	<z-angle to="133" val="60.81"/>
	<z-angle to="313" val="60.81"/>
	<z-angle to="333" val="60.81"/>
	<z-angle to="213" val="50"/>
	<z-angle to="323" val="50"/>
	<z-angle to="233" val="50"/>
	<z-angle to="123" val="50"/>

        <s-distance to="113" val="1732" />
        <s-distance to="313" val="1732" />
        <s-distance to="333" val="1732" />
        <s-distance to="133" val="1732" />
        <s-distance to="213" val="1414" />
        <s-distance to="323" val="1414" />
        <s-distance to="233" val="1414" />
        <s-distance to="123" val="1414" />

      </obs>
    </points-observations>
  </network>
</gama-local>
